# Litecoin regtest configuration for Bitcoin Computer Node
server=1
regtest=1
txindex=1
listen=1
printtoconsole=1

# RPC settings
rpcuser=bcn-admin
rpcpassword=kH4nU5Okm6-uyC0_mA5ztVNacJqZbYd_KGLl6mx722A=
rpcport=19332
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

# P2P settings
port=19444

# ZMQ settings
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28332

# Performance
dbcache=512
maxmempool=256

# Wallet
deprecatedrpc=accounts
fallbackfee=0.0001
