
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  // MongoDB does not use file-based migrations — use `prisma db push` instead
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
